### ISSUE TITLE
ImportError: cannot import name 'static_class' from 'floris.tools'

### ISSUE THREAD

**Issue by KeosWang** [soanagno/wakeNet#3]
Hello Author!

I'm lucky to have found the code you've written, it's simply fantastic. I'm currently working on something related as well, so I found your code on github and tried to reproduce your work.

However, I encountered certain problems when running it, so I hope you can help me out.

I set train_net to 0, make_data to true and save_data to false in the inputs_curl. json file in the example_inputs folder, did the same in the inputs_gauss. json and ran it as per your instructions! example_main.py file, but it still shows the error. After consulting and trying several times, I still have no solution, so I have no choice but to ask you for help. I hope you can help me. Thank you anyway.

Below is the error message:
Traceback (most recent call last).
  File "c:\Users\lll\Desktop\Code\python_code\wakenet-master\Code\example_main.py", line 1, in <module>
    from neuralWake import *
  File "c:\Users\lll\Desktop\Code\python_code\wakenet-master\Code\neuralWake.py", line 2, in <module>
    from initialisations import *
  File "c:\Users\lll\Desktop\Code\python_code\wakenet-master\Code\initialisations.py", line 5, in <module>
    from floris.tools import static_class as sc
ImportError: cannot import name 'static_class' from 'floris.tools' (D:\anaconda\lib\site-packages\floris\tools\__init__.py)

I'm looking forward to hearing from you soon!

Best regards,
Keos

**Comment by soanagno** [comment]
Dear Keos,

Thank you for your kind words. The error you are encountering is due to a custom version of the Floris code which was written specifically to resize the wakes of the Curl model (this was not available in the original Floris repo at the time).

I recommend to not import any modules which are not included in the original Floris repo to avoid the errors you are getting.

Best,
Sokratis

**Comment by soanagno** [comment]
Dear Keos,

Thank you for your kind words. The error you are encountering is due to a custom version of the Floris code which was written specifically to resize the wakes of the Curl model (this was not available in the original Floris repo at the time).

I recommend to not import any modules which are not included in the original Floris repo to avoid the errors you are getting.

Best,
Sokratis
